#!/usr/bin/env python3
"""Generate comprehensive skill audit markdown report."""
import json
from pathlib import Path
from datetime import datetime


def generate_audit():
    """Generate skill audit markdown."""
    skills_dir = Path("aria_skills")
    skills = []
    
    # Scan all skill directories
    for skill_path in sorted(skills_dir.iterdir()):
        if skill_path.name.startswith("_") or skill_path.name == "__pycache__":
            continue
        if not skill_path.is_dir():
            continue
            
        skill_json = skill_path / "skill.json"
        skill_md = skill_path / "SKILL.md"
        init_py = skill_path / "__init__.py"
        
        if skill_json.exists():
            try:
                with open(skill_json) as f:
                    data = json.load(f)
                skills.append({
                    "name": data.get("name", skill_path.name),
                    "dir": skill_path.name,
                    "layer": data.get("layer", 3),
                    "category": data.get("category", "unknown"),
                    "tools": data.get("tools", []),
                    "dependencies": data.get("dependencies", []),
                    "has_doc": skill_md.exists(),
                    "has_impl": init_py.exists(),
                    "deprecated": data.get("deprecated", False),
                })
            except json.JSONDecodeError:
                print(f"Warning: Invalid JSON in {skill_json}")
                continue
    
    # Generate markdown
    layers = {0: [], 1: [], 2: [], 3: [], 4: []}
    for skill in skills:
        layers[skill["layer"]].append(skill)
    
    md = f"""# Aria Skills Audit Report

> **Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M UTC")}  
> **Total Skills:** {len(skills)}

---

## Summary

- **Active Skills:** {len([s for s in skills if not s['deprecated']])}
- **Deprecated:** {len([s for s in skills if s['deprecated']])}
- **Documentation Coverage:** {len([s for s in skills if s['has_doc']])}/{len(skills)} ({len([s for s in skills if s['has_doc']])*100//len(skills)}%)
- **Implementation Status:** {len([s for s in skills if s['has_impl']])}/{len(skills)} ({len([s for s in skills if s['has_impl']])*100//len(skills)}%)

### Layer Distribution

| Layer | Count | Category |
|-------|-------|----------|
| L0 - Security | {len(layers[0])} | Kernel-level security validation |
| L1 - Infrastructure | {len(layers[1])} | API clients, database access |
| L2 - Core Services | {len(layers[2])} | Essential system services |
| L3 - Domain Skills | {len(layers[3])} | Business logic, integrations |
| L4 - Orchestration | {len(layers[4])} | Multi-skill coordination |

---

## Skills by Layer

"""
    
    layer_names = {
        0: "L0 - Security",
        1: "L1 - Infrastructure",
        2: "L2 - Core Services",
        3: "L3 - Domain Skills",
        4: "L4 - Orchestration"
    }
    
    for layer_num in [0, 1, 2, 3, 4]:
        if not layers[layer_num]:
            continue
        md += f"\n### {layer_names[layer_num]}\n\n"
        md += "| Skill | Category | Tools | Docs | Status |\n"
        md += "|-------|----------|-------|------|--------|\n"
        
        for skill in sorted(layers[layer_num], key=lambda s: s['name']):
            doc_icon = "yes" if skill['has_doc'] else "no"
            status = "deprecated" if skill['deprecated'] else "active"
            tool_count = len(skill['tools'])
            md += f"| {skill['name']} | {skill['category']} | {tool_count} | {doc_icon} | {status} |\n"

    # Add dependency analysis
    md += "\n---\n\n## Dependency Analysis\n\n"
    deprecated_deps = []
    for skill in skills:
        if "database" in skill['dependencies']:
            deprecated_deps.append(skill['name'])
    
    if deprecated_deps:
        md += f"WARNING: Skills with deprecated dependencies: {', '.join(deprecated_deps)}\n\n"
    else:
        md += "No deprecated dependencies detected.\n\n"
    
    # Add documentation gaps
    md += "## Documentation Status\n\n"
    missing_docs = [s['name'] for s in skills if not s['has_doc']]
    if missing_docs:
        md += f"Missing SKILL.md: {', '.join(missing_docs)}\n\n"
    else:
        md += "All skills documented (100% coverage).\n\n"
    
    md += f"\n---\n\n*Auto-generated by scripts/generate_skill_audit.py*\n"
    
    print(md)


if __name__ == "__main__":
    generate_audit()
